### PR TITLE
Skip ownership check for resources with `exists` annotation

### LINKED ISSUE #457: Getting ownership error when using `exists` annotation for resources created by kapp-controller App CRs
**What steps did you take:**
`kapp deploy -a myapp -f one.yaml -f two.yaml`

`one.yaml` has an App CR which internally creates a CRD (C).
`two.yaml` has a mock CRD (C) with the [exists](https://carvel.dev/kapp/docs/v0.46.0/apply/#kappk14sioexists) annotation and a CR of kind (C)

**What happened:**
When I tried deploying myapp again I got ownership error
```
kapp deploy -a myapp -f one.yaml -f two.yaml
kapp: Error: Ownership errors:
- Resource 'customresourcedefinition/customresource.mydomain.io (apiextensions.k8s.io/v1) cluster' is already associated with a different app
```

**What did you expect:**
The app should have been successfully deployed the second time as well.

**Anything else you would like to add:**
[Slack thread](https://kubernetes.slack.com/archives/CH8KCCKA5/p1647515383756429)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by praveenrewar**
#### What this PR does / why we need it:
Skip ownership check for resources with `kapp.k14s.io/exists` and `kapp.k14s.io/noop` annotations as these resources could be created by another kapp app.

#### Which issue(s) this PR fixes:

Fixes #457 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

##### Review Checklist:

- [x] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [x] Relevant tests are added or updated
- [x] Relevant docs in this repo added or updated
- [x] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [x] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by 100mik — APPROVED** [review]
Much TDD 😆 
LGTM!

File: test/e2e/exists_ann_test.go [hunk 1]
```diff
@@ -44,12 +47,12 @@ metadata:
 
 	go func() {
 		time.Sleep(2 * time.Second)
-		NewClusterResource(t, externalResourceKind, externalResourceName, "", kubectl)
+		NewClusterResourceFromYaml(t, namespace, kubectl)
```
Comment (cppforlife) [inline test/e2e/exists_ann_test.go]: Yaml => YAML

File: pkg/kapp/resources/labeled_resources.go [hunk 2]
```diff
@@ -13,6 +13,11 @@ import (
 	"k8s.io/apimachinery/pkg/labels"
 )
 
+const (
+	ExistsAnnKey = "kapp.k14s.io/exists" // Value is ignored
+	NoopAnnKey   = "kapp.k14s.io/noop"   // value is ignored
```
Comment (cppforlife) [inline pkg/kapp/resources/labeled_resources.go:18]: any reason why we should move NoopAnnKey into this package?

Comment (praveenrewar) [reply pkg/kapp/resources/labeled_resources.go:18]: I was thinking of skipping the check for `noop` annotation as well, but later on just added the question to get thoughts from everyone.
> Question: Should we do it for kapp.k14s.io/noop as well?

File: test/e2e/exists_ann_test.go (hunk 1 above)
Comment (praveenrewar) [reply test/e2e/exists_ann_test.go]: Done.

File: pkg/kapp/resources/labeled_resources.go (hunk 2 above)
Comment (cppforlife) [reply pkg/kapp/resources/labeled_resources.go:18]: hmm, i see. i dont have a strong use case in mind for noop being checked as well. may be @100mik got something on his mind?

Comment (100mik) [reply pkg/kapp/resources/labeled_resources.go:18]: In theory, if a user does apply the noop annotation to a resource associated with another `kapp` application, I think  it will error out in a similar way, since this error occurs while listing existing resources. 

I remember Joe using `--dangerous-override-ownership-of-existing-resources` as a workaround when he was figuring out how package repos with overlapping packages should work. (illustrated in test defined [here](https://github.com/vmware-tanzu/carvel-kapp/pull/483/files#diff-8057c511c4ba289c2097cd0883396a1e1e672d86c719534c414c411de578febdR1))

Comment (praveenrewar) [reply pkg/kapp/resources/labeled_resources.go:18]: Cool. I will skip the check for resources with noop annotation as well.

File: pkg/kapp/resources/labeled_resources.go [hunk 3]
```diff
@@ -144,7 +149,9 @@ func (a *LabeledResources) checkResourceOwnership(resources []Resource, opts All
 	var errs []error
 
 	for _, res := range resources {
-		if val, found := res.Labels()[expectedLabelKey]; found {
+		val, hasExpectedLabelKey := res.Labels()[expectedLabelKey]
+		_, hasExistsAnnotation := res.Annotations()[ExistsAnnKey]
```
Comment (praveenrewar) [inline pkg/kapp/resources/labeled_resources.go]: I just realised that the `res` over here is an existing resource and not a new resource. The test case is passing because the exists ann is also added to the resource deployed via kubectl. I will make relevant changes.

Comment (praveenrewar) [reply pkg/kapp/resources/labeled_resources.go]: Done

File: pkg/kapp/resources/labeled_resources.go [hunk 4]
```diff
@@ -135,6 +143,28 @@ func (a *LabeledResources) AllAndMatching(newResources []Resource, opts AllAndMa
 	return resources, nil
 }
 
+func (a *LabeledResources) resourcesForOwnershipCheck(newResources []Resource, nonLabeledResources []Resource) []Resource {
```
Comment (cppforlife) [inline pkg/kapp/resources/labeled_resources.go:146]: nit: can drop receiver name `a`

File: pkg/kapp/resources/labeled_resources.go [hunk 5]
```diff
@@ -135,6 +143,28 @@ func (a *LabeledResources) AllAndMatching(newResources []Resource, opts AllAndMa
...
+		if hasExistsAnnotation || hasNoopAnnotation {
+			resourcesToBeSkipped[NewUniqueResourceKey(res).String()] = true
+		}
+	}
+
+	for _, res := range nonLabeledResources {
+		if !resourcesToBeSkipped[NewUniqueResourceKey(res).String()] {
+			resources = append(resources, res)
+		}
+	}
```
Comment (cppforlife) [inline pkg/kapp/resources/labeled_resources.go:163]: dont we actually want to verify the ownership of non-new resources as well? or is this not how it works today since because we only find non labeled resources based on new resources?

File: pkg/kapp/resources/labeled_resources.go (hunk 4 above)
Comment (praveenrewar) [reply pkg/kapp/resources/labeled_resources.go:146]: Sure.

File: pkg/kapp/resources/labeled_resources.go (hunk 5 above)
Comment (praveenrewar) [reply pkg/kapp/resources/labeled_resources.go:163]: (I  have read it a few times, but I am still not sure if I have understood it properly 😅 )

> or is this not how it works today since because we only find non labeled resources based on new resources?

Yeah, we find the non labeled resources based on the new resources and the labeled resources. 
https://github.com/vmware-tanzu/carvel-kapp/blob/31e7abfc48f00ab81fda9ca0235062e9e33ca7c1/pkg/kapp/resources/labeled_resources.go#L213
