### PR TITLE
Set default for Kubernetes service port

### LINKED ISSUE #615: kapp deploy fails when K8s server host, port and kubeconfig is passed as env and port is empty.
**What steps did you take:**
kapp deploy fails when K8s server host, port and kubeconfig is passed as env and port is empty.

**To reproduce the issue**
```
$ export KUBERNETES_SERVICE_HOST=32.123.12.123
$ export KUBERNETES_SERVICE_PORT=
$ export KAPP_KUBECONFIG_YAML=`
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:...
    server: https://${KAPP_KUBERNETES_SERVICE_HOST_PORT}
    ....
.....
`
$ kapp deploy -a samplepackage-ctrl -f package-resources.yml --kubeconfig=/dev/null
```

**What happened:**
kapp deploy errors out with following error:
```
kapp: Error: yaml: line 5: mapping values are not allowed in this context
```

**What did you expect:**
kapp deploy to succeed.

**Anything else you would like to add:**
Issue is easily reproducible on GKE cluster.

**Environment:**

- kapp version (use `kapp --version`):
- OS (e.g. from `/etc/os-release`):
- Kubernetes version (use `kubectl version`)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by vicmarbev**
Signed-off-by: Víctor Martínez Bevià <vicmarbev@gmail.com>

#### What this PR does / why we need it:

Sets a default for the Kubernetes service port, so it does not fail when it is not provided.

#### Which issue(s) this PR fixes:

Fixes #615 

#### Does this PR introduce a user-facing change?

```release-note

```

##### Review Checklist:

- [ ] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [ ] Relevant tests are added or updated
- [ ] Relevant docs in this repo added or updated
- [ ] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [ ] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by rohitagg2020** [comment]
LGTM

File: pkg/kapp/cmd/core/config_factory.go [hunk 1]
```diff
@@ -113,7 +113,12 @@ func (f *ConfigFactoryImpl) clientConfig() (bool, clientcmd.ClientConfig, error)
 	}
 
 	if len(configYAML) > 0 {
-		envHostPort := net.JoinHostPort(os.Getenv("KUBERNETES_SERVICE_HOST"), os.Getenv("KUBERNETES_SERVICE_PORT"))
+		// If it is not provided, we default the Kubernetes service port to 443
+		kubernetesServicePort, ok := os.LookupEnv("KUBERNETES_SERVICE_PORT")
```
Comment (praveenrewar) [inline pkg/kapp/cmd/core/config_factory.go]: `ok` will be true if the environment variable is set to empty string (which can be the case sometimes), so I think we can just go ahead with `Getenv` and checking on empty string.

File: pkg/kapp/cmd/core/config_factory.go [hunk 2]
```diff
@@ -113,7 +113,12 @@ func (f *ConfigFactoryImpl) clientConfig() (bool, clientcmd.ClientConfig, error)
...
+		if !ok {
+			kubernetesServicePort = "443"
+		}
+		envHostPort := net.JoinHostPort(os.Getenv("KUBERNETES_SERVICE_HOST"), kubernetesServicePort)
```
Comment (praveenrewar) [inline pkg/kapp/cmd/core/config_factory.go]: Instead of manually adding the port when it is empty, let's not use the `JoinHostPort` (which adds the `:` at the end) and directly use the host. client-go will manually add the port based on `http`/`https`.

File: pkg/kapp/cmd/core/config_factory.go (hunk 1 above)
Comment (vicmarbev) [reply pkg/kapp/cmd/core/config_factory.go]: I didn't think of that!

File: pkg/kapp/cmd/core/config_factory.go (hunk 2 above)
Comment (vicmarbev) [reply pkg/kapp/cmd/core/config_factory.go]: Sure!

**Review by praveenrewar — APPROVED** [review]
LGTM!

**Comment by rohitagg2020** [comment]
LGTM
