### PR TITLE
Skip API operations for diff run

### LINKED ISSUE #791: `kapp deploy --diff-run` should not require updating the existing ConfigMap
**What steps did you take:**
- Executed `kapp deploy --app "svc-kapp" --diff-run -f kapp.yaml` for an _existing_ app `svc-kapp`.

**What happened:**
- Error:
```
kapp: Error: Updating app: configmaps "svc-kapp" is forbidden:

  User "xxxxx" cannot update resource "configmaps" in API group "" in the namespace "svc"
```

**What did you expect:**
- A diff of the changes to be displayed with no errors and no further action.

**Anything else you would like to add:**
- My primary use case for this feature is displaying configuration changes raised in a pull request or on a branch during which CI should have read-only permissions in the cluster.

**Environment:**

- kapp version (use `kapp --version`): v0.58.0
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04 LTS (GitHub Actions)
- Kubernetes version (use `kubectl version`): v1.24.15

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by vixus0**
#### What this PR does / why we need it:

Diff run should be usable when the authorised RBAC role doesn't have
write permissions for resources in the cluster.

Diff run on app creation used the dry run feature of the Kubernetes
API, to avoid persisting kapp ConfigMap changes. However this still
checks RBAC permissions, and errored if the role did not have write
permissions for ConfigMaps.

The kapp ConfigMap was also being updated when doing a diff run for an
existing app.

This skips the API operations for updating the ConfigMap when doing a
diff run.

#### Which issue(s) this PR fixes:

Fixes #791

#### Does this PR introduce a user-facing change?

```release-note
- Diff run will not check anymore for appropriate RBAC permissions.
```

##### Review Checklist:

- [x] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [x] Relevant tests are added or updated
- [ ] Relevant docs in this repo added or updated
- [ ] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [ ] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by vixus0** [comment]
Hmm, not sure why the new test `TestDiffRunReadOnlyContext` is failing. On my machine with minikube v1.31.1 (kubernetes v1.27.3):
```
=== RUN   TestDiffRunReadOnlyContext
Running 'kapp delete -a test-e2e-rbac-app -n kapp-test --yes'...
Running 'kapp delete -a diff-run-read-only -n kapp-test --yes'...
Running 'kapp deploy -a test-e2e-rbac-app -f - -n kapp-test --yes'...
Running 'kubectl get secret scoped-sa -o jsonpath={.data.token} -n kapp-test'...
Running 'kubectl config view --minify -o jsonpath={.clusters[].name} -n kapp-test'...
Running 'kubectl -redacted-'...
Running 'kubectl config set-context scoped-context --user=scoped-user --cluster=minikube'...
==> diff-run using scoped context
Running 'kapp deploy -f - -a diff-run-read-only --diff-run --kubeconfig-context=scoped-context -n kapp-test --into-ns kapp-test --yes'...
Running 'kubectl get configmap diff-run-read-only -n kapp-test -o yaml -n kapp-test'...
Running 'kubectl config delete-context scoped-context -n kapp-test'...
Running 'kubectl config delete-user scoped-user -n kapp-test'...
Running 'kapp delete -a test-e2e-rbac-app -n kapp-test --yes'...
Running 'kapp delete -a diff-run-read-only -n kapp-test --yes'...
--- PASS: TestDiffRunReadOnlyContext (0.52s)
```

The other two tests (`TestFormattedError`, `TestIgnoreFailingAPIServices`) seem to be failing on the `develop` branch also, but I can investigate further.

**Comment by praveenrewar** [comment]
Hey @vixus0! Thank you so much for the PR. Like you mentioned the other 2 tests are failing on develop as well, most probably because of some changes in the latest version of Kubernetes. I will fix them as soon as I get some time.
Regarding the new test, I will have to take a closer look to be sure what the issue is. Is it consistently working for you on your machine?

**Comment by vixus0** [comment]
Yeah, I can consistently run the test on my machine. It seems in CI the initial `kapp deploy` step for actually setting up the scoped role is failing:

```
kapp: Error: waiting on reconcile secret/scoped-sa (v1) namespace: kapp-test:
  Errored:
    Getting resource secret/scoped-sa (v1) namespace: kapp-test:
      API server says: secrets "scoped-sa" not found (reason: NotFound)
```

File: pkg/kapp/app/recorded_app.go [hunk 1]
```diff
@@ -132,6 +133,10 @@ func (a *RecordedApp) UpdateUsedGVsAndGKs(gvs []schema.GroupVersion, gks []schem
 func (a *RecordedApp) CreateOrUpdate(prevAppName string, labels map[string]string, isDiffRun bool) (bool, error) {
 	defer a.logger.DebugFunc("CreateOrUpdate").Finish()
 
+	if isDiffRun {
```
Comment (praveenrewar) [inline pkg/kapp/app/recorded_app.go]: Now that I think about it, we don't need to pass it down to any other function (except for create). Instead, whenever an app is found and if diffRun is true, we can just return without calling the other functions.
Examples:
```go
	if foundMigratedApp {
		a.isMigrated = true
		if isDiffRun {
			return false, nil
		}
		return false, a.updateApp(app, labels)
	}
```
or 
```go
	if foundNonMigratedApp {
		if isDiffRun {
			return false, nil
		}
		if a.isMigrationEnabled() {
			return false, a.migrate(app, labels, a.fqName())
		}
		return false, a.updateApp(app, labels)
	}
```

We exit [pretty early](https://github.com/carvel-dev/kapp/blob/0c34e94eeac6573dc38960fbbd68db789558150d/pkg/kapp/cmd/app/deploy.go#L181) in deploy if diff Run is true, so we won't have to worry about other update cases where UsedGVs and UsedGKs are updated.

File: test/e2e/diff_test.go [hunk 2]
```diff
@@ -402,3 +403,85 @@ metadata:
...
+  name: scoped-sa
+  namespace: __ns__
+roleRef:
+  apiGroup: rbac.authorization.k8s.io
+  kind: Role
+  name: scoped-role
+  namespace: __ns__
+`
+
+	rbac = strings.ReplaceAll(rbac, "__ns__", env.Namespace)
```
Comment (praveenrewar) [inline test/e2e/diff_test.go]: nit: We don't need to provide namespace for the resources (unless we want them to be created in different namespaces), we can use the IntoNs opt instead ([example](https://github.com/carvel-dev/kapp/blob/0c34e94eeac6573dc38960fbbd68db789558150d/test/e2e/app_change_test.go#L48)).

File: test/e2e/diff_test.go [hunk 3]
```diff
@@ -402,3 +403,85 @@ metadata:
...
+metadata:
+  name: config
+`
+
+	logger.Section("diff-run using scoped context", func() {
+		_, _ = kapp.RunWithOpts([]string{"deploy", "-f", "-", "-a", appName, "--diff-run", fmt.Sprintf("--kubeconfig-context=%s", scopedContext)},
+			RunOpts{IntoNs: true, AllowError: false, StdinReader: strings.NewReader(yaml1)})
+
+		NewMissingClusterResource(t, "configmap", appName, env.Namespace, kubectl)
+	})
```
Comment (praveenrewar) [inline test/e2e/diff_test.go:478]: Could you also add a test for update scenario?

**Review by praveenrewar — COMMENTED** [review]
I re ran the tests and the test seems to be passing now (except the other 2, I have created a PR to fix them), I am guessing it was a one time thing, although I am not sure how that error could possible come.
Left some comments.

File: pkg/kapp/app/recorded_app.go (hunk 1 above)
Comment (vixus0) [reply pkg/kapp/app/recorded_app.go]: Great, I've removed the `isDiffRun` field from the `RecordedApp` struct and moved the conditions to `CreateOrUpdate`.

File: test/e2e/diff_test.go (hunk 3 above)
Comment (vixus0) [reply test/e2e/diff_test.go:478]: Done, added to the `TestDiffRunReadOnlyContext` test. Let me know if it should be a completely separate test case instead..

File: test/e2e/diff_test.go [hunk 4]
```diff
@@ -402,3 +403,99 @@ metadata:
 
 	NewMissingClusterResource(t, "configmap", name, env.Namespace, kubectl)
 }
+
+func TestDiffRunReadOnlyContext(t *testing.T) {
```
Comment (praveenrewar) [inline test/e2e/diff_test.go]: Maybe?
```suggestion
func TestDiffRun_WithReadOnlyPermissions(t *testing.T) {
```

File: test/e2e/diff_test.go [hunk 5]
```diff
@@ -402,3 +403,99 @@ metadata:
...
+	yaml1 := `
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: config
+`
+
+	logger.Section("diff-run app create using read-only role", func() {
+		_, _ = kapp.RunWithOpts([]string{"deploy", "-f", "-", "-a", appName, "--diff-run", fmt.Sprintf("--kubeconfig-context=%s", scopedContext)},
+			RunOpts{IntoNs: true, AllowError: false, StdinReader: strings.NewReader(yaml1)})
```
Comment (praveenrewar) [inline test/e2e/diff_test.go]: nit: We don't need `_, _` since we are not using the values. `AllowError` is by default false. (Same in other places)
```suggestion
	logger.Section("diff-run app create using read-only role", func() {
		kapp.RunWithOpts([]string{"deploy", "-f", "-", "-a", appName, "--diff-run", fmt.Sprintf("--kubeconfig-context=%s", scopedContext)},
			RunOpts{IntoNs: true, StdinReader: strings.NewReader(yaml1)})
```

File: test/e2e/diff_test.go [hunk 6]
```diff
@@ -402,3 +403,99 @@ metadata:
...
+		_, _ = kapp.RunWithOpts([]string{"deploy", "-f", "-", "-a", appName},
+			RunOpts{IntoNs: true, AllowError: false, StdinReader: strings.NewReader(yaml1)})
+
+		NewPresentClusterResource("configmap", appName, env.Namespace, kubectl)
+
+		_, _ = kapp.RunWithOpts([]string{"deploy", "-f", "-", "-a", appName, "--diff-run", fmt.Sprintf("--kubeconfig-context=%s", scopedContext)},
+			RunOpts{IntoNs: true, AllowError: false, StdinReader: strings.NewReader(yaml2)})
+
+		c := NewPresentClusterResource("configmap", appName, env.Namespace, kubectl)
+		require.NotContains(t, c.res.Annotations(), "foo", "Expected configmap to not have foo annotation")
```
Comment (praveenrewar) [inline test/e2e/diff_test.go]: I am not sure why we are checking for this annotation on the meta configmap. The annotation has been added to the resource that kapp is deploying so it shouldn't effect the meta configmap at all (even if diff run isn't being used). 
I think the fact that kapp deploy with diff-run worked without any error and with read permissions only should be enough to say that the meta configmap wasn't updated.

**Review by praveenrewar — COMMENTED** [review]
Looking really good now 🚀  
Just left some minor comments.

**Comment by praveenrewar** [comment]
The PR to fix the other 2 tests is merged, so you can rebase on those changes now for the tests to pass.

File: test/e2e/diff_test.go (hunk 6 above)
Comment (vixus0) [reply test/e2e/diff_test.go]: You're right, I misread which configmap was being checked. I won't bother checking for the annotation if we're satisfied when the diff-run works without errors.

**Review by praveenrewar — APPROVED** [review]
LGTM! Thank you so much for the PR @vixus0 🚀
