### PR TITLE
Obj null check to avoid failure on non-typed character like NULL as value for array type key/object

### LINKED ISSUE #89: kapp template rules do not work against non-typed fields such as `initContainers: null`
When trying to deploy the [bitnami postgresql chart](https://github.com/bitnami/charts/blob/301bb18b0f8455d6f64c26aedd50ee9d7c74c221/bitnami/postgresql/templates/statefulset.yaml#L74) as part of cf-for-k8s via kapp, we get the following error:

`
kapp: Error: ObjectRefSetMod for path 'spec,template,spec,initContainers,(all),env,(all),valueFrom,configMapKeyRef' on resource 'statefulset/cf-db-postgresql (apps/v1) namespace: cf-db': Unexpected non-array found: <nil>
`

The relevant configuration yaml looks like this (with irrelevant lines omitted):

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cf-db-postgresql
spec:
  template:
    spec:
      initContainers: null
```

When we try to deploy the same YAML with `kubectl apply -f`, we don't get any error.

We're using kapp version 0.22.0.

Thanks!
Jen & @jamespollard8

### PR DESCRIPTION
**Pull request by kumaritanushree**
#### What this PR does / why we need it:
Added null check to avoid non-typed character error (like envFrom: null/<empty>) while applying template rules in case of versioned resources.
#### Which issue(s) this PR fixes:

Fixes #89 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

##### Review Checklist:

- [x] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [x] Relevant tests are added or updated
- [ ] Relevant docs in this repo added or updated
- [ ] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [x] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by 100mik — DISMISSED** [review]
LGTM

File: test/e2e/non_typed_char_error_test.go [hunk 1]
```diff
@@ -0,0 +1,62 @@
+// Copyright 2020 VMware, Inc.
```
Comment (praveenrewar) [inline test/e2e/non_typed_char_error_test.go]: nit: 2020 -> 2022 and new line after the headers.

File: test/e2e/non_typed_char_error_test.go [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+// SPDX-License-Identifier: Apache-2.0
+package e2e
+
+import (
+	"strings"
+	"testing"
+)
+
+func TestNonTypedCharError(t *testing.T) {
```
Comment (praveenrewar) [inline test/e2e/non_typed_char_error_test.go]: TestNonTypedArrayFields ? (Might as well want to change the file name and name on line number 49 based on this).

File: test/e2e/non_typed_char_error_test.go [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+        envFrom:
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: simple-cm
+  annotations:
+    kapp.k14s.io/versioned: ""
+data:
+  hello_msg: carvel
```
Comment (praveenrewar) [inline test/e2e/non_typed_char_error_test.go]:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
spec:
  template:
    spec:
      initContainers: null
```
Should we add this from the issue?

File: test/e2e/non_typed_char_error_test.go (hunk 2 above)
Comment (kumaritanushree) [reply test/e2e/non_typed_char_error_test.go]: updated

File: test/e2e/non_typed_char_error_test.go (hunk 3 above)
Comment (kumaritanushree) [reply test/e2e/non_typed_char_error_test.go]: updated

File: test/e2e/non_typed_char_error_test.go (hunk 1 above)
Comment (kumaritanushree) [reply test/e2e/non_typed_char_error_test.go]: done

File: test/e2e/non_typed_char_error_test.go (hunk 2 above)
Comment (100mik) [reply test/e2e/non_typed_char_error_test.go]: very nitty, but on a second thought should the name point out that it is testing template rules in this case? (`TestTemplateRulesWithNonTypedArrayFields` maybe, even though it is a mouthful)

Do not feel very strongly about this but I think it does not hurt to be more explicit

File: test/e2e/non_typed_array_fields_test.go [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+spec:
+  ports:
+  - port: 80
+    name: test
+  clusterIP: None
+  selector:
+    app: simple-svc
+---
+apiVersion: apps/v1
+kind: StatefulSet
```
Comment (100mik) [inline test/e2e/non_typed_array_fields_test.go]: nit: I think we changed it to a StatefulSet to address the example in the original issue,

However, I think a Deployment pod template could have both `envFrom: null` and `initContainers:`.
Thought I would point that out since a StatefulSet "does more" than a Deployment and that is not something we require for this case.

**Review by 100mik — COMMENTED** [review]
Just a thought

File: test/e2e/non_typed_char_error_test.go (hunk 2 above)
Comment (kumaritanushree) [reply test/e2e/non_typed_char_error_test.go]: Agree as this says exactly where the issue was. Let wait for other's opinion on it. @praveenrewar

Comment (praveenrewar) [reply test/e2e/non_typed_char_error_test.go]: Works for me 👍🏻

File: test/e2e/non_typed_array_fields_test.go (hunk 4 above)
Comment (praveenrewar) [reply test/e2e/non_typed_array_fields_test.go]: Yeah, I was thinking of just keeping the StatefulSet, right now I think the Service and the ConfigMap don't mean anything in the test. We can keep the previous example of Deployment and ConfigMap if we want, and add the initContainers along with envFrom 👍🏻

**Review by rohitagg2020 — APPROVED** [review]

**Review by 100mik — APPROVED** [review]
Ship it! 🚢
