### PR TITLE
#156 adopting resource with versioned annotations

### LINKED ISSUE #156: kapp should be able to adopt resource with vesioned annotation
kapp should be able to adopt resources annotated with `kapp.k14s.io/versioned: ""` that are deployed previously with a tool other than kapp. Currently kapp panics.
kapp could 'adopt' a resource by deleting the one currently in the cluster and creating a new one.

Reproduction steps:
1. Deploy a [versioned resource](https://github.com/k14s/kapp/blob/7cc75a5363584520d2bc8a7bd021c8350716edd3/docs/diff.md#versioned-resources) with `kubectl`
2. Deploy the versioned resource again with `kapp`
3. kapp results in this error:
```
panic: Missing template version

goroutine 1 [running]:
github.com/k14s/kapp/pkg/kapp/diff.TemplateResource.Version(0x20c3440, 0xc0004121e0, 0x0, 0x0, 0x0, 0x1)
	github.com/k14s/kapp@/pkg/kapp/diff/template_resource.go:40 +0x153
github.com/k14s/kapp/pkg/kapp/diff.ChangeSetWithTemplates.assignNewNames(0xc00007b9a0, 0x1, 0x1, 0xc000539620, 0x1, 0x1, 0xc00010c7e0, 0x2, 0x2, 0x1, ...)
	github.com/k14s/kapp@/pkg/kapp/diff/change_set_with_templates.go:105 +0x196
github.com/k14s/kapp/pkg/kapp/diff.ChangeSetWithTemplates.Calculate(0xc00007b9a0, 0x1, 0x1, 0xc000539620, 0x1, 0x1, 0xc00010c7e0, 0x2, 0x2, 0x1, ...)
	github.com/k14s/kapp@/pkg/kapp/diff/change_set_with_templates.go:37 +0x19c
github.com/k14s/kapp/pkg/kapp/cmd/app.(*DeployOptions).calculateAndPresentChanges(0xc0002b7200, 0xc00007b9a0, 0x1, 0x1, 0xc000539620, 0x1, 0x1, 0xc0004229c0, 0x1, 0x1, ...)
	github.com/k14s/kapp@/pkg/kapp/cmd/app/deploy.go:311 +0x3d6
github.com/k14s/kapp/pkg/kapp/cmd/app.(*DeployOptions).Run(0xc0002b7200, 0x0, 0x0)
	github.com/k14s/kapp@/pkg/kapp/cmd/app/deploy.go:136 +0x7db
github.com/k14s/kapp/pkg/kapp/cmd/app.NewDeployCmd.func1(0xc0002eb680, 0xc0002fc9c0, 0x0, 0x4, 0xc0003c5c80, 0xc000127be0)
	github.com/k14s/kapp@/pkg/kapp/cmd/app/deploy.go:48 +0x2a
github.com/k14s/kapp/pkg/kapp/cmd.NewKappCmd.func1.1(0xc0002eb680, 0xc0002fc9c0, 0x0, 0x4, 0x0, 0x0)
	github.com/k14s/kapp@/pkg/kapp/cmd/kapp.go:124 +0xcc
github.com/cppforlife/cobrautil.ReconfigureLeafCmd.func1(0xc0002eb680, 0xc0002fc9c0, 0x0, 0x4, 0x0, 0x0)
	github.com/cppforlife/cobrautil@v0.0.0-20200108171912-b289811fd2b9/misc.go:67 +0x135
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc0002eb680, 0xc0002fc9c0, 0x0, 0x4, 0x0, 0x0)
	github.com/cppforlife/cobrautil@v0.0.0-20200108171912-b289811fd2b9/misc.go:25 +0xaf
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc0002eb680, 0xc0002fc9c0, 0x0, 0x4, 0x0, 0x0)
	github.com/cppforlife/cobrautil@v0.0.0-20200108171912-b289811fd2b9/misc.go:25 +0xaf
github.com/spf13/cobra.(*Command).execute(0xc0002eb680, 0xc0002fc940, 0x4, 0x4, 0xc0002eb680, 0xc0002fc940)
	github.com/spf13/cobra@v0.0.3/command.go:762 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002eac80, 0xc0002eac80, 0xc0002fd7c0, 0x103b33a)
	github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	github.com/k14s/kapp@/cmd/kapp/kapp.go:27 +0x16f
```

### PR DESCRIPTION
**Pull request by sethiyash**

### CODE REVIEW

File: test/e2e/annotations_test.go [hunk 1]
```diff
@@ -431,9 +433,80 @@ metadata:
...
+	}
+
+	cleanUp()
+	defer cleanUp()
+
+	logger.Section("Kapp should adopt already deployed versioned resource through kubectl", func() {
+		out, _ := kubectl.RunWithOpts([]string{"apply", "-f", "-", "-o", "json"},
+			RunOpts{IntoNs: true, StdinReader: strings.NewReader(yaml)})
+
+		respKubectl := appv1alpha1.App{}
```
Comment (cppforlife) [inline test/e2e/annotations_test.go]: not sure why we are deserializing into App CR. we should use corev1.ConfigMap type (as that what that is).

Comment (sethiyash) [reply test/e2e/annotations_test.go]: Yeah my bad. Done with the changes.
