### PR TITLE
make diff-exit-status work for app-group deployments

### LINKED ISSUE #166: Unexpected result of diff-exit-status for app group deploy
When passing the `diff-exit-status` flag to an app group deployment, kapp exits after checking the first app inside the app group.

When applied to app groups, I would expect kapp to exit after checking all apps inside the group and returning the exit status for the complete group (unchanged, any resource has changed etc.).

### PR DESCRIPTION
**Pull request by twiechert**
fixes https://github.com/vmware-tanzu/carvel-kapp/issues/166 by making app-group deployments not fail if a single app returns exit status 2 or 3.

### CODE REVIEW

File: pkg/kapp/cmd/appgroup/deploy.go [hunk 1]
```diff
@@ -68,11 +70,22 @@ func (o *DeployOptions) Run() error {
 		return err
 	}
 
+	var exitCode float64 = 0
 	// TODO is there some order between apps?
 	for _, appGroupApp := range updatedApps {
 		err := o.deployApp(appGroupApp)
 		if err != nil {
-			return err
+			if reflect.TypeOf(err).Name() == "DeployDiffExitStatus" {
```
Comment (cppforlife) [inline pkg/kapp/cmd/appgroup/deploy.go]: i think we should be able to check err like so:

```
if deployErr, ok := err.(cmdapp.DeployDiffExitStatus); ok {
  ...
}
```

File: pkg/kapp/cmd/appgroup/deploy.go [hunk 2]
```diff
@@ -68,11 +70,22 @@ func (o *DeployOptions) Run() error {
...
+				var deployErr cmdapp.DeployDiffExitStatus = err.(cmdapp.DeployDiffExitStatus)
+
+				if deployErr.ExitStatus() == 1 {
+					return err
+				}
```
Comment (cppforlife) [inline pkg/kapp/cmd/appgroup/deploy.go]: it never return 1 today. instead of checking on ExitStatus, if we were able to type cast into DeployDiffExitStatus then we are working with either no changes or pending changes. no need to double check that.

File: pkg/kapp/cmd/appgroup/deploy.go [hunk 3]
```diff
@@ -68,11 +70,22 @@ func (o *DeployOptions) Run() error {
...
+				exitCode = math.Max(exitCode, float64(deployErr.ExitStatus()))
+
```
Comment (cppforlife) [inline pkg/kapp/cmd/appgroup/deploy.go]: nit: remove newline

File: pkg/kapp/cmd/appgroup/deploy.go [hunk 4]
```diff
@@ -96,6 +109,11 @@ func (o *DeployOptions) Run() error {
 		}
 	}
 
+	if o.AppFlags.DiffFlags.Run && o.AppFlags.DiffFlags.ExitStatus {
+		var hasNoChanges = exitCode < 3
```
Comment (cppforlife) [inline pkg/kapp/cmd/appgroup/deploy.go]: lets do a more explicit check here: cmdapp.DeployDiffExitStatus{HasNoChanges: exitCode == 2}

**Comment by twiechert** [comment]
very valid points, thanks for the review.

File: pkg/kapp/cmd/appgroup/deploy.go [hunk 5]
```diff
@@ -68,11 +68,16 @@ func (o *DeployOptions) Run() error {
 		return err
 	}
 
+	var exitCode float64 = 0
 	// TODO is there some order between apps?
 	for _, appGroupApp := range updatedApps {
 		err := o.deployApp(appGroupApp)
 		if err != nil {
-			return err
+            if deployErr, ok := err.(cmdapp.DeployDiffExitStatus); ok {
```
Comment (cppforlife) [inline pkg/kapp/cmd/appgroup/deploy.go]: nit: looks like formatting is a bit off

Comment (twiechert) [reply pkg/kapp/cmd/appgroup/deploy.go]: image
I think the diff view is misleading, also the linters don't indicate anything malformed.

Comment (cppforlife) [reply pkg/kapp/cmd/appgroup/deploy.go]: it seems that if is indented via spaces whereas the rest of the code is indented via tabs, and thats why it shows up at different invent levels in github and not in your editor.

Comment (twiechert) [reply pkg/kapp/cmd/appgroup/deploy.go]: replaced whitestaces by tabs.

does anything speak against adding - gofmt to the linters section as part of the .golangci.yml?
