### PR TITLE
[Draft] Adding resource filter for labels (#272)

### LINKED ISSUE #272: support filtering resources by label in kapp deploy
**What steps did you take:**
```bash
:; kapp deploy -a 'label:!undefined' -f path/to/yaml
```

**What happened:**
```
kapp: Error: Expected label selector to check for equality
```

**What did you expect:**
I expected kapp to deploy all the resources in the yaml since none have a label w/ the key "undefined", and the expression in the attempted command line is supposed to be valid.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- kapp version (use `kapp --version`): 0.37.0
- OS (e.g. from `/etc/os-release`):
- Kubernetes version (use `kubectl version`)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by renuy**
@rohitagg2020

### CODE REVIEW

File: pkg/kapp/resources/resource_filter.go [hunk 1]
```diff
@@ -92,6 +94,26 @@ func (f ResourceFilter) Matches(resource Resource) bool {
...
+			expectedLabelKey, expectedLabelVal, err := NewSimpleLabel(labelSelector).KV()
+			if err != nil {
+				return false
+			}
+			if val, found := resource.Labels()[expectedLabelKey]; found {
+				if val == expectedLabelVal {
+					matched = true
+					break
+				}
+			}
```
Comment (cppforlife) [inline pkg/kapp/resources/resource_filter.go]: instead of doing manual matching, lets use https://github.com/vmware-tanzu/carvel-kapp/blob/e0bf1c9d485c5c59a23b4cfe75915782e7fb4b42/vendor/k8s.io/apimachinery/pkg/labels/selector.go#L38. this gives us ability to work with label selectors like: `!key`, `key=foo`, `key!=foo` etc.

File: pkg/kapp/resources/resource_filter.go [hunk 2]
```diff
@@ -5,6 +5,7 @@ package resources
 
 import (
 	"encoding/json"
+	"k8s.io/apimachinery/pkg/labels"
```
Comment (cppforlife) [inline pkg/kapp/resources/resource_filter.go]: nit: third party exports go into the next section

File: pkg/kapp/resources/resource_filter.go [hunk 3]
```diff
@@ -92,6 +94,26 @@ func (f ResourceFilter) Matches(resource Resource) bool {
 		}
 	}
 
+	if len(f.Labels) > 0 {
+		var matched bool
```
Comment (praveenrewar) [inline pkg/kapp/resources/resource_filter.go:99]: Should we introduce a separate method for this flag like BoolFilter? Maybe we can do this later and do it for a few other flags as well.

Comment (praveenrewar) [reply pkg/kapp/resources/resource_filter.go:99]: However, the code is readable, so we can definitely skip it.

File: pkg/kapp/resources/resource_filter.go (hunk 1 above)
Comment (renuy) [reply pkg/kapp/resources/resource_filter.go]: done. Please check

File: pkg/kapp/resources/resource_filter.go (hunk 2 above)
Comment (renuy) [reply pkg/kapp/resources/resource_filter.go]: done

**Review by rohitagg2020 — APPROVED** [review]

File: pkg/kapp/resources/resource_filter.go [hunk 4]
```diff
@@ -92,6 +94,24 @@ func (f ResourceFilter) Matches(resource Resource) bool {
 		}
 	}
 
+	if len(f.Labels) > 0 {
+		var matched bool = false
```
Comment (cppforlife) [inline pkg/kapp/resources/resource_filter.go]: no need to set `= false`

File: pkg/kapp/resources/resource_filter.go [hunk 5]
```diff
@@ -92,6 +94,24 @@ func (f ResourceFilter) Matches(resource Resource) bool {
...
+		for _, label := range f.Labels {
+			labelSelector, err := labels.Parse(label)
+			if err != nil {
+				return false
```
Comment (cppforlife) [inline pkg/kapp/resources/resource_filter.go]: i wonder if we should panic here for now, since otherwise we are swallowing error and skipping other matchers. eventually we could add Validate() may be to ResourceFilter.

File: pkg/kapp/resources/resource_filter.go [hunk 6]
```diff
@@ -92,6 +94,24 @@ func (f ResourceFilter) Matches(resource Resource) bool {
...
+			}
+			labelsSet := labels.Set(resource.Labels())
+			if labelSelector.Matches(labelsSet) {
```
Comment (cppforlife) [inline pkg/kapp/resources/resource_filter.go]: lets inline labelsSet since it's just a cast. eg

```
if labelSelector.Matches(labels.Set(resource.Labels())) {
```

File: test/e2e/label_filter_test.go [hunk 7]
```diff
@@ -0,0 +1,90 @@
...
+// SPDX-License-Identifier: Apache-2.0
+
+package e2e
+
+import (
+	"strings"
+	"testing"
+)
+
+func TestLabelFilter(t *testing.T) {
```
Comment (cppforlife) [inline test/e2e/label_filter_test.go]: for this functionality having an e2e test is quite heavy. i would recommend adding a unit test against ResourceFilter class directly.

if this is the only e2e test that touches filtering i would modify it a bit to be more generic, eg
- test 2 filter flags in combination
- test --filter

also we do not need to actually deploy things, just have to check against diff summary since that's what filter applies to.

File: test/e2e/label_filter_test.go [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+	})
+
+	logger.Section("deploy initial", func() {
+		kapp.RunWithOpts([]string{"deploy", "-f", "-", "-a", name, "--filter-labels", "x!=y"}, RunOpts{IntoNs: true, StdinReader: strings.NewReader(yaml1)})
+
+		NewMissingClusterResource(t, "service", "redis-primary", env.Namespace, kubectl)
+		NewPresentClusterResource("configmap", "redis-config", env.Namespace, kubectl)
+		NewPresentClusterResource("configmap", "redis-config2", env.Namespace, kubectl)
+	})
+
```
Comment (cppforlife) [inline test/e2e/label_filter_test.go]: nit: extra newline

**Review by 100mik — APPROVED** [review]

File: pkg/kapp/resources/resource_filter.go (hunk 5 above)
Comment (renuy) [reply pkg/kapp/resources/resource_filter.go]: will panic.

File: pkg/kapp/resources/resource_filter.go (hunk 6 above)
Comment (renuy) [reply pkg/kapp/resources/resource_filter.go]: ok

File: test/e2e/label_filter_test.go (hunk 7 above)
Comment (renuy) [reply test/e2e/label_filter_test.go]: if out of the two filter flags, one is "--filter" then it will always take precedence. other filter flag (like labels or kind or nz etc) will not get applied. Hence adding test with filter-label and filter-kind together.
Found testing with table output better than testing with json output.

**Review by sethiyash — APPROVED** [review]

File: test/e2e/filter_test.go [hunk 9]
```diff
@@ -0,0 +1,127 @@
...
+			RunOpts{IntoNs: true, StdinReader: strings.NewReader(yaml1)})
+
+		if !strings.Contains(out, expectedOutput2) {
+			t.Fatalf("Did not find expected diff output >>%s<< in >>%s<<", out, expectedOutput2)
+		}
+	})
+
+	logger.Section("test filter flag", func() {
+		out, _ := kapp.RunWithOpts([]string{"deploy", "-f", "-", "-a", name, "--diff-run",
+			"--filter", "{\"resource\":{\"kinds\":[\"Service\"]}}"},
```
Comment (cppforlife) [inline test/e2e/filter_test.go]: tip: this is a good case to use ` for wrapping string so that you dont have escape " with slashes.

File: test/e2e/filter_test.go [hunk 10]
```diff
@@ -0,0 +1,127 @@
...
+import (
+	"strings"
+	"testing"
+)
+
+func TestFilter(t *testing.T) {
+	env := BuildEnv(t)
+	logger := Logger{}
+	kapp := Kapp{t, env.Namespace, env.KappBinaryPath, logger}
+	expectedOutput1 := `
```
Comment (cppforlife) [inline test/e2e/filter_test.go]: good pattern to follow here is to put expected "material" as close as possible to the assertion itself.

Comment (renuy) [reply test/e2e/filter_test.go]: Done

File: test/e2e/filter_test.go (hunk 9 above)
Comment (renuy) [reply test/e2e/filter_test.go]: done
