### PR TITLE
handling invalid memory address or nil pointer dereference (#328)

### LINKED ISSUE #328: Command "kapp deploy --diff-summary=false -a test -f abc.yml", panics  due to  runtime error: invalid memory address or nil pointer dereference
**What steps did you take:**
Ran the following command (--diff-summary=false)
kapp deploy --diff-summary=false -a test -f abc.yml

**What happened:**
Panic as follows:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x22a1d1c]

goroutine 1 [running]:
github.com/k14s/kapp/pkg/kapp/clusterapply.(*ChangesCountsView).Strings(0x0, 0xc00020b000, 0x8, 0x9, 0xc0006a7a20)
	github.com/k14s/kapp/pkg/kapp/clusterapply/changes_view.go:236 +0x13c
github.com/k14s/kapp/pkg/kapp/clusterapply.(*ChangesCountsView).String(0x0, 0x295b380, 0xc0000c13c0)
	github.com/k14s/kapp/pkg/kapp/clusterapply/changes_view.go:259 +0x30
github.com/k14s/kapp/pkg/kapp/clusterapply.(*ChangesView).Summary(...)
	github.com/k14s/kapp/pkg/kapp/clusterapply/changes_view.go:136
github.com/k14s/kapp/pkg/kapp/clusterapply.(*ChangeSetView).Summary(...)
	github.com/k14s/kapp/pkg/kapp/clusterapply/change_set_view.go:49
github.com/k14s/kapp/pkg/kapp/cmd/app.(*DeployOptions).calculateAndPresentChanges(0xc0000fe580, 0x0, 0x0, 0x0, 0xc0004e9800, 0x2, 0x2, 0xc0005b6480, 0x1, 0x1, ...)
	github.com/k14s/kapp/pkg/kapp/cmd/app/deploy.go:367 +0xe05
github.com/k14s/kapp/pkg/kapp/cmd/app.(*DeployOptions).Run(0xc0000fe580, 0x0, 0x0)
	github.com/k14s/kapp/pkg/kapp/cmd/app/deploy.go:143 +0x958
github.com/k14s/kapp/pkg/kapp/cmd/app.NewDeployCmd.func1(0xc0000feb00, 0xc0008c9630, 0x0, 0x5, 0xc0003c4c00, 0x29350c0)
	github.com/k14s/kapp/pkg/kapp/cmd/app/deploy.go:54 +0x2a
github.com/k14s/kapp/pkg/kapp/cmd.NewKappCmd.func1.1(0xc0000feb00, 0xc0008c9630, 0x0, 0x5, 0x0, 0x0)
	github.com/k14s/kapp/pkg/kapp/cmd/kapp.go:128 +0xb8
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc0000feb00, 0xc0008c9630, 0x0, 0x5, 0x0, 0x0)
	github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0xb2
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc0000feb00, 0xc0008c9630, 0x0, 0x5, 0x0, 0x0)
	github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0xb2
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc0000feb00, 0xc0008c9630, 0x0, 0x5, 0x0, 0x0)
	github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0xb2
github.com/spf13/cobra.(*Command).execute(0xc0000feb00, 0xc0008c95e0, 0x5, 0x5, 0xc0000feb00, 0xc0008c95e0)
	github.com/spf13/cobra@v1.1.3/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003822c0, 0xc0003822c0, 0xc0000c13c0, 0x3d005b8)
	github.com/spf13/cobra@v1.1.3/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:895
main.nonExitingMain(0x0, 0x0)
	github.com/k14s/kapp/cmd/kapp/kapp.go:42 +0x167
main.main()
	github.com/k14s/kapp/cmd/kapp/kapp.go:21 +0x26

**What did you expect:**
deploy command without a diff summary

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- kapp version (use `kapp --version`): 0.40.0
- OS (e.g. from `/etc/os-release`): 
- Kubernetes version (use `kubectl version`)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by renuy**

### CODE REVIEW

File: pkg/kapp/clusterapply/change_set_view.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ func (v *ChangeSetView) Print(ui ui.UI) {
 		}
 	}
 
-	v.changesView = &ChangesView{ChangeViews: v.changeViews, Sort: true}
+	v.changesView = &ChangesView{ChangeViews: v.changeViews, Sort: true, countsView: NewChangesCountsView()}
```
Comment (praveenrewar) [inline pkg/kapp/clusterapply/change_set_view.go:41]: On line number 49, should we call the `v.changesView.Summary()` function only when `v.opts.Summary` is true? 
Based on the comment, it is assumed that `Print()` function is used before `Summary()`, but when `--diff-summary` is set to false, `Print()` is not called.

Comment (praveenrewar) [inline pkg/kapp/clusterapply/change_set_view.go:41]: On line number 49, should we call the `v.changesView.Summary()` function only when `v.opts.Summary` is true?
Based on the comment, it is assumed that `Print()` function is used before `Summary()`, but when `--diff-summary` is set to false, `Print()` is not called.
Also, technically, `Summary()` should not be used if `--diff-summary` is set to false.

Comment (renuy) [reply pkg/kapp/clusterapply/change_set_view.go:41]: that was also an option. however, since the flag is passed to NewChangeSetView, felt it should be the job of changeSetView object to decide whether it should show summary or not.
Which is it is deciding in change_set_view.go, line 43. This is to handle un-initialized object.
